version: '3.1'

services:

  mongo_db:
    image: mongo
    restart: always
    ports:
      - "27019:27017" # Use port 27019 to avoid conflicts with any other running Mongo instance
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo_seeder:
    build:
      context: .
      dockerfile: mongo-seeder.Dockerfile
    depends_on:
      - mongo_db

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@mongo_db:27017/
